<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_FileTxt.txt</name>
   <tag></tag>
   <elementGuidId>5fdce5ac-ecd3-42a0-a93b-183afdc54fd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='FileTxt.txt']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.sendbird-file-message-item-body__file-name__text.sendbird-label.sendbird-label--body-1.sendbird-label--color-onbackground-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7b40f1ad-973e-4d37-a857-753fbf3e5ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sendbird-file-message-item-body__file-name__text sendbird-label sendbird-label--body-1 sendbird-label--color-onbackground-1</value>
      <webElementGuid>3b9b1e3b-6425-4aa6-b541-281863154a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>sendbird-file-message-item-body__file-name__text</value>
      <webElementGuid>e5b2a5fa-168e-4405-9707-b51f8238f3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FileTxt.txt</value>
      <webElementGuid>0e5bd4f7-7d85-46c9-9c94-604ac2d35d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;sendbird-app__wrap&quot;]/div[@class=&quot;sendbird-app__conversation-wrap&quot;]/div[@class=&quot;sendbird-conversation&quot;]/div[@class=&quot;sendbird-conversation__messages sendbird-conversation__message-list&quot;]/div[@class=&quot;sendbird-conversation__scroll-container&quot;]/div[@class=&quot;sendbird-conversation__messages-padding&quot;]/div[@class=&quot;sendbird-msg-hoc sendbird-msg--scroll-ref&quot;]/div[@class=&quot;sendbird-message-hoc__message-content sendbird-message-content incoming&quot;]/div[@class=&quot;sendbird-message-content__middle&quot;]/div[@class=&quot;sendbird-message-content__middle__body-container&quot;]/div[@class=&quot;sendbird-message-content__middle__message-item-body sendbird-file-message-item-body incoming mouse-hover&quot;]/div[@class=&quot;sendbird-file-message-item-body__file-name sendbird-color--onbackground-1 sendbird-textbutton&quot;]/span[@class=&quot;sendbird-file-message-item-body__file-name__text sendbird-label sendbird-label--body-1 sendbird-label--color-onbackground-1&quot;]</value>
      <webElementGuid>9b0f2e56-556c-42f1-aeb4-845337425a88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/div[2]/div/div[2]/div[5]/div/div[2]/div/div/div[2]/span</value>
      <webElementGuid>6e173c0c-f286-45ec-874b-b4475b1b415f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello'])[1]/following::span[7]</value>
      <webElementGuid>6768a7fb-22f6-434d-aef4-ca75b7cb9645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pratama16'])[1]/following::span[8]</value>
      <webElementGuid>b01541f1-1c09-4939-a2e7-333aa0f65b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter message'])[1]/preceding::span[4]</value>
      <webElementGuid>db8ea4de-60c5-48f0-9135-782b98eb3bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FileTxt.txt']/parent::*</value>
      <webElementGuid>2d55f94a-5b5e-402d-9bc7-e369814cf7d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/div[2]/span</value>
      <webElementGuid>ccce6c33-01a0-47da-a1fb-4d5645fa9ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'FileTxt.txt' or . = 'FileTxt.txt')]</value>
      <webElementGuid>0cc6378b-84b7-4a9d-9a74-00c1017588f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
