<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect_Dark theme_fill</name>
   <tag></tag>
   <elementGuidId>f549768f-b51c-4c0c-9e62-fbe68ba3e496</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>rect.fill</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>4a9d5d39-a419-4da9-b281-6f274ecd4b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>7f35dd9c-1566-4bcb-84d2-bd2f378d1007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>f4282eab-4fb6-4264-8130-226b9ef585f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>4d27fd35-6774-4e05-8159-c7dda554af9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>17af2c3d-b4b7-4a21-aa51-420b8f8bd68c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>ad9f29e4-beb6-4d36-a4de-8103690068b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#000</value>
      <webElementGuid>67c01dc0-7898-48fb-ad97-d23f2c6d68e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rx</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>cb083153-e2ba-4b26-a1db-d574ad2ad86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sendbird-modal-root&quot;)/div[@class=&quot;sendbird-modal&quot;]/div[@class=&quot;sendbird-modal__content&quot;]/div[@class=&quot;sendbird-modal__body&quot;]/span[@class=&quot;sendbird-label sendbird-label--subtitle-1 sendbird-label--color-onbackground-2&quot;]/form[@class=&quot;sendbird-edit-user-profile&quot;]/section[@class=&quot;sendbird-edit-user-profile__theme&quot;]/div[@class=&quot;sendbird-edit-user-profile__theme__theme-icon&quot;]/div[@class=&quot;sendbird-icon sendbird-icon-toggle-off&quot;]/svg[1]/g[1]/g[1]/g[1]/rect[@class=&quot;fill&quot;]</value>
      <webElementGuid>bf771c0f-3371-462a-ac31-992cff63582e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
