<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Group</name>
   <tag></tag>
   <elementGuidId>e6c0e621-e36d-4ad0-90ba-3defcc013289</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Group']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.sendbird-label.sendbird-label--subtitle-1.sendbird-label--color-onbackground-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c22d1af5-ceb1-4e2b-bec9-ea5fe8471cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sendbird-label sendbird-label--subtitle-1 sendbird-label--color-onbackground-1</value>
      <webElementGuid>567c2208-3c40-412d-be70-ed8a71b6b9b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Group</value>
      <webElementGuid>df6df325-ab4c-4797-8e69-3c3df4aafc67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sendbird-modal-root&quot;)/div[@class=&quot;sendbird-modal sendbird-add-channel__modal&quot;]/div[@class=&quot;sendbird-modal__content&quot;]/div[@class=&quot;sendbird-modal__body&quot;]/span[@class=&quot;sendbird-label sendbird-label--subtitle-1 sendbird-label--color-onbackground-2&quot;]/div[@class=&quot;sendbird-add-channel__rectangle-wrap&quot;]/div[@class=&quot;sendbird-add-channel__rectangle&quot;]/span[@class=&quot;sendbird-label sendbird-label--subtitle-1 sendbird-label--color-onbackground-1&quot;]</value>
      <webElementGuid>4be969e5-882b-4152-9fc8-7ddd003703d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sendbird-modal-root']/div/div/div[2]/span/div/div/span</value>
      <webElementGuid>825899bd-6e58-44e2-a8d5-021a7c33674a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New channel'])[1]/following::span[3]</value>
      <webElementGuid>55e65201-3361-4b15-ae5b-04f219bba676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No channels'])[2]/following::span[4]</value>
      <webElementGuid>02f4f92f-e5a9-4eb4-8152-411b3a8ddafb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Group']/parent::*</value>
      <webElementGuid>4da1e41e-8a4f-421e-94da-8d0cc8a434b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/span</value>
      <webElementGuid>9df92900-73b8-4605-923e-272ec1c02413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Group' or . = 'Group')]</value>
      <webElementGuid>c24b6e13-2567-4eaf-997c-a44033d109ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
