<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pratama18_sendbird-checkbox--checkmark</name>
   <tag></tag>
   <elementGuidId>5cd4b2ee-899f-4677-8398-9c53f57dafa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.sendbird-checkbox--checkmark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>41768cf3-449e-4b41-a505-c5b8efb21d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sendbird-checkbox--checkmark </value>
      <webElementGuid>e742c26f-dc92-4360-a707-38578ea43a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sendbird-modal-root&quot;)/div[@class=&quot;sendbird-modal&quot;]/div[@class=&quot;sendbird-modal__content&quot;]/div[@class=&quot;sendbird-modal__body&quot;]/span[@class=&quot;sendbird-label sendbird-label--subtitle-1 sendbird-label--color-onbackground-2&quot;]/div[1]/div[@class=&quot;sendbird-create-channel--scroll&quot;]/div[@class=&quot;sendbird-user-list-item&quot;]/label[@class=&quot;sendbird-user-list-item__checkbox&quot;]/label[@class=&quot;sendbird-checkbox&quot;]/span[@class=&quot;sendbird-checkbox--checkmark&quot;]</value>
      <webElementGuid>efeab7d0-4858-4ce3-a7c5-929b1642dbce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sendbird-modal-root']/div/div/div[2]/span/div/div/div/label/label/span</value>
      <webElementGuid>25336d60-e17c-46ad-b33d-7dc3efe2f91b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>d60fe6b8-2f7b-4ac1-bf16-67bd44b67408</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
