<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Halo</name>
   <tag></tag>
   <elementGuidId>2a0362f2-9a13-4e47-8c3f-720c08b8a836</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sendbird-channel-preview__content__lower</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>402d6b61-6182-4486-926e-db98e6a6dce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sendbird-channel-preview__content__lower</value>
      <webElementGuid>e05ea5d5-b547-4500-8cad-b2633a9538c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Halo</value>
      <webElementGuid>05e64ac5-2167-4880-af3a-1f013b0fbf73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;sendbird-app__wrap&quot;]/div[@class=&quot;sendbird-app__channellist-wrap&quot;]/div[@class=&quot;sendbird-channel-list&quot;]/div[@class=&quot;sendbird-channel-list__body&quot;]/div[1]/div[@class=&quot;sendbird-channel-preview sendbird-channel-preview--active&quot;]/div[@class=&quot;sendbird-channel-preview__content&quot;]/div[@class=&quot;sendbird-channel-preview__content__lower&quot;]</value>
      <webElementGuid>ef029d84-6465-4b5a-944a-ff7cf6448425</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/div[2]/div[2]</value>
      <webElementGuid>a6a669e0-42bf-4b02-9909-0f693919b02f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pratama18, Pratama17'])[1]/following::div[1]</value>
      <webElementGuid>a12d470e-b625-49b5-9f7b-c781db138e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pratama16'])[2]/following::div[18]</value>
      <webElementGuid>e70b5856-b8be-4a10-bc76-667e462d899f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pratama18, Pratama17'])[2]/preceding::div[14]</value>
      <webElementGuid>82e62283-893b-495a-9c51-e781d702aa2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]</value>
      <webElementGuid>84e1fa5f-897b-47bd-979e-16b16b6862c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Halo' or . = 'Halo')]</value>
      <webElementGuid>36733bbf-6ce6-465e-94d6-938b81adbc5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
